name: RegEx Issue Title Labeler
on:
  issues:
    types: [opened, edited]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
    - name: Apply Label
      uses: tycrek/issue-labeler@v2.2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
        enable-versioned-regex: 0
